# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('BR', 'Buyer/Renter'), ('PO', 'Private Owner'), ('B', 'Broker'), ('RC', 'Real Estate Company')], max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
