# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('lang', models.IntegerField()),
                ('latt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('img', models.CharField(max_length=100)),
                ('nrooms', models.IntegerField()),
                ('ntoilets', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.Client')),
            ],
        ),
    ]
