# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20160401_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lang',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='latt',
            field=models.CharField(max_length=50),
        ),
    ]
