# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20160401_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='government',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='saleOrRent',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
